'use strict';
const fullName = 'Carolyne Golias';
console.log('value of fullName:', fullName);
const isCool = true;
console.log('value of isCool:', isCool);
const totalPets = 2;
console.log('value of totalPets:', totalPets);
console.log('typeof fullname:', typeof 'Carolyne Golias');
console.log('typeof isCool', typeof true);
console.log('typeof totalPets', typeof 2);
const empty = null;
console.log('the value of empty:', empty);
console.log('typeof empty:', typeof null);
const nothing = undefined;
console.log('the value of nothing:', undefined);
console.log('typeof nothing', typeof nothing);
