'use strict';
const width = 10;
const height = 20;
const area = width * height;
console.log('the value of the area is:', area);
console.log('the typeof area is:', typeof area);
const bill = 44;
const payment = 100;
const change = payment - bill;
console.log('the value of change:', change);
console.log('the typeof change:', typeof change);
const quizzes = 55;
const midterm = 77;
const final = 99;
const grade = (quizzes + midterm + final) / 3;
console.log('the value of grade:', grade);
console.log('the typeof grade:', typeof grade);
const firstName = 'Carolyne';
const lastName = 'Golias';
const fullName = firstName + ' ' + lastName;
console.log('the value of fullName', fullName);
console.log('typeof fullName', typeof fullName);
const pH = 4;
const isAcidic = pH < 7;
console.log('the value of isAcidic', isAcidic);
console.log('the typeof isAcidic', typeof isAcidic);
const headCount = 5;
const isSparta = headCount === 300;
console.log('the value of isSparta', isSparta);
console.log('the typeof isSparta', typeof isSparta);
let motto = fullName;
motto += ' is the GOAT.';
console.log('the value of motto', motto);
console.log('the typeof motto', typeof motto);
